# Generated by Django 5.1 on 2026-02-01 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_payment_created_by_visit_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.JSONField(default=list, help_text='List of working days (0=Mon, 1=Tue, ..., 6=Sun)')),
                ('start_time', models.TimeField(help_text='Clinic opening time')),
                ('end_time', models.TimeField(help_text='Clinic closing time')),
                ('slot_duration', models.PositiveIntegerField(default=30, help_text='Appointment slot duration in minutes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic Schedule',
                'verbose_name_plural': 'Clinic Schedule',
            },
        ),
    ]
